import { Prisma, type Sprint, type Comment } from "@prisma/client";

export const DEMO_PROJECT_ID = "init-project-id-dq8yh-d0as89hjd";
export const DEMO_PROJECT_KEY = "CQC";
export const DEMO_ADMIN_ID = "demo_admin";
export const DEMO_MANAGER_ID = "demo_quality_manager";
export const DEMO_TESTER_ID = "demo_quality_tester";
export const DEMO_INSPECTOR_L1_ID = "demo_quality_inspector_l1";
export const DEMO_INSPECTOR_L2_ID = "demo_quality_inspector_l2";
export const LEGACY_DEMO_USER_IDS = [
  "user_2PwZmH2xP5aE0svR6hDH4AwDlcu",
  "user_2PwYvTgm6kvgJIbWwN0xsei8izu",
  "user_2PvBRngdvenUlFvQNAWbXIvYVy5",
] as const;

const legacyIssueNames = [
  "Issue descriptions can contain code snippets",
  "Issue types can be changed, click here and try it out!",
  "Think Different Odyssey",
  "Visionary Ventures",
];

export function isLegacyDemoIssue(name: string) {
  return legacyIssueNames.includes(name);
}

export const defaultUsers = [
  {
    id: DEMO_ADMIN_ID,
    name: "AD",
    email: "admin@construction-qc.demo",
    avatar:
      "https://images.clerk.dev/uploaded/img_2PwZslOi493tjduHiBADgDxhHlg.png",
    role: "ADMIN",
  },
  {
    id: DEMO_MANAGER_ID,
    name: "QM",
    email: "quality.manager@construction-qc.demo",
    avatar:
      "https://images.clerk.dev/uploaded/img_2PwjGSsR9nGqEhAyt5nydgXhBI1.webp",
    role: "QUALITY_MANAGER",
  },
  {
    id: DEMO_TESTER_ID,
    name: "QT",
    email: "quality.tester@construction-qc.demo",
    avatar:
      "https://images.clerk.dev/uploaded/img_2Pwinee7Eg6qoSgqailCZSJt3uS.webp",
    role: "QUALITY_TESTER",
  },
  {
    id: DEMO_INSPECTOR_L1_ID,
    name: "QI1",
    email: "quality.inspector.l1@construction-qc.demo",
    avatar:
      "https://images.clerk.dev/uploaded/img_2PwjGSsR9nGqEhAyt5nydgXhBI1.webp",
    role: "QUALITY_INSPECTOR_L1",
  },
  {
    id: DEMO_INSPECTOR_L2_ID,
    name: "QI2",
    email: "quality.inspector.l2@construction-qc.demo",
    avatar:
      "https://images.clerk.dev/uploaded/img_2Pwinee7Eg6qoSgqailCZSJt3uS.webp",
    role: "QUALITY_INSPECTOR_L2",
  },
] as const;

export function generateInitialUserComments(userId: string): Comment[] {
  const now = new Date();
  const suffix = userId ? userId.slice(0, 8) : "initdemo";

  return [
    {
      id: `comment-a-${suffix}`,
      content:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Moisture cans verified. Chainage and truck docket attached before testing started.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
      authorId: DEMO_TESTER_ID,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      isEdited: false,
      issueId: `issue-2-${suffix}`,
      logId: null,
    },
    {
      id: `comment-b-${suffix}`,
      content:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"L1 inspection completed. Results are within the acceptance band for placement release.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
      authorId: DEMO_INSPECTOR_L1_ID,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      isEdited: false,
      issueId: `issue-3-${suffix}`,
      logId: null,
    },
    {
      id: `comment-c-${suffix}`,
      content:
        '{"root":{"children":[{"children":[{"detail":0,"format":0,"mode":"normal","style":"","text":"Approved for close-out. Upload final signed record in the daily QA pack.","type":"text","version":1}],"direction":"ltr","format":"","indent":0,"type":"paragraph","version":1}],"direction":"ltr","format":"","indent":0,"type":"root","version":1}}',
      authorId: DEMO_INSPECTOR_L2_ID,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      isEdited: false,
      issueId: `issue-5-${suffix}`,
      logId: null,
    },
  ];
}

export function generateInitialUserSprints(userId: string): Sprint[] {
  const now = new Date();
  const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);
  const twoWeeks = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);
  const suffix = userId ? userId.slice(0, 8) : "initdemo";

  return [
    {
      id: `sprint-a-${suffix}`,
      name: "Zone A Soil Moisture Round 1",
      description: "Field testing and first-line review for the current working layer.",
      duration: "1 week",
      startDate: now,
      endDate: nextWeek,
      creatorId: userId,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      status: "ACTIVE",
    },
    {
      id: `sprint-b-${suffix}`,
      name: "Zone B Soil Moisture Round 1",
      description: "Pending test lot release for the next haul sequence.",
      duration: "1 week",
      startDate: nextWeek,
      endDate: twoWeeks,
      creatorId: userId,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      status: "PENDING",
    },
  ];
}

export function generateInitialUserIssues(
  userId: string
): Prisma.IssueUncheckedCreateInput[] {
  const now = new Date();
  const suffix = userId ? userId.slice(0, 8) : "initdemo";
  const activeSprintId = `sprint-a-${suffix}`;
  const pendingSprintId = `sprint-b-${suffix}`;

  const issues: Prisma.IssueUncheckedCreateInput[] = [
    {
      id: `issue-1-${suffix}`,
      key: "ISSUE-1",
      name: "Soil Moisture Test Lot 12, Chainage 0+120 to 0+180",
      description: null,
      status: "IN_PROGRESS",
      type: "TASK",
      sprintPosition: 1,
      boardPosition: 1,
      reporterId: DEMO_MANAGER_ID,
      assigneeId: DEMO_TESTER_ID,
      parentId: null,
      sprintId: activeSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 2,
      chainage: "0+120 to 0+180",
      truckDetails: "Truck 14 and Truck 18",
      sampleLabel: "LOT12-R1",
      initialWeight: null,
      finalWeight: null,
      moistureWeight: null,
      moisturePct: null,
      levelOneStatus: "PENDING",
      levelOneNote: null,
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-2-${suffix}`,
      key: "ISSUE-2",
      name: "Test Instance A - Truck 14 discharge",
      description: null,
      status: "IN_PROGRESS",
      type: "SUBTASK",
      sprintPosition: 2,
      boardPosition: 2,
      reporterId: DEMO_TESTER_ID,
      assigneeId: DEMO_TESTER_ID,
      parentId: `issue-1-${suffix}`,
      sprintId: activeSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 1,
      chainage: "0+135",
      truckDetails: "Truck 14 / Load 03",
      sampleLabel: "SM-A1",
      initialWeight: 1260.5,
      finalWeight: 1182.4,
      moistureWeight: 78.1,
      moisturePct: 6.61,
      levelOneStatus: "PENDING",
      levelOneNote: null,
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-3-${suffix}`,
      key: "ISSUE-3",
      name: "Test Instance B - Truck 18 discharge",
      description: null,
      status: "INSPECTION",
      type: "SUBTASK",
      sprintPosition: 3,
      boardPosition: 1,
      reporterId: DEMO_TESTER_ID,
      assigneeId: DEMO_INSPECTOR_L1_ID,
      parentId: `issue-1-${suffix}`,
      sprintId: activeSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 1,
      chainage: "0+165",
      truckDetails: "Truck 18 / Load 07",
      sampleLabel: "SM-B1",
      initialWeight: 1215.2,
      finalWeight: 1148.9,
      moistureWeight: 66.3,
      moisturePct: 5.77,
      levelOneStatus: "OK",
      levelOneNote: "Accepted for L2 review.",
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-4-${suffix}`,
      key: "ISSUE-4",
      name: "Soil Moisture Test Access Road Layer 2, Chainage 1+020 to 1+080",
      description: null,
      status: "INSPECTION",
      type: "TASK",
      sprintPosition: 4,
      boardPosition: 2,
      reporterId: DEMO_MANAGER_ID,
      assigneeId: DEMO_INSPECTOR_L1_ID,
      parentId: null,
      sprintId: activeSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 1,
      chainage: "1+020 to 1+080",
      truckDetails: "Truck 05",
      sampleLabel: "AR-L2",
      initialWeight: null,
      finalWeight: null,
      moistureWeight: null,
      moisturePct: null,
      levelOneStatus: "OK",
      levelOneNote: "Field record complete.",
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-5-${suffix}`,
      key: "ISSUE-5",
      name: "Test Instance C - Access Road verification sample",
      description: null,
      status: "DONE",
      type: "SUBTASK",
      sprintPosition: 5,
      boardPosition: 1,
      reporterId: DEMO_TESTER_ID,
      assigneeId: DEMO_INSPECTOR_L2_ID,
      parentId: `issue-4-${suffix}`,
      sprintId: activeSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 1,
      chainage: "1+060",
      truckDetails: "Truck 05 / Spot check",
      sampleLabel: "AR-C1",
      initialWeight: 1188.4,
      finalWeight: 1129.7,
      moistureWeight: 58.7,
      moisturePct: 5.2,
      levelOneStatus: "OK",
      levelOneNote: "Checked against site sheet.",
      levelTwoStatus: "OK",
      levelTwoNote: "Closed out in QA register.",
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-6-${suffix}`,
      key: "ISSUE-6",
      name: "Soil Moisture Test Stockpile Rework Area",
      description: null,
      status: "TODO",
      type: "TASK",
      sprintPosition: 1,
      boardPosition: -1,
      reporterId: DEMO_ADMIN_ID,
      assigneeId: DEMO_MANAGER_ID,
      parentId: null,
      sprintId: null,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 2,
      chainage: "Stockpile rework area",
      truckDetails: "Awaiting allocation",
      sampleLabel: "SR-01",
      initialWeight: null,
      finalWeight: null,
      moistureWeight: null,
      moisturePct: null,
      levelOneStatus: "PENDING",
      levelOneNote: null,
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
    {
      id: `issue-7-${suffix}`,
      key: "ISSUE-7",
      name: "Test Instance D - Stockpile trial sample",
      description: null,
      status: "TODO",
      type: "SUBTASK",
      sprintPosition: 2,
      boardPosition: -1,
      reporterId: DEMO_MANAGER_ID,
      assigneeId: DEMO_TESTER_ID,
      parentId: `issue-6-${suffix}`,
      sprintId: pendingSprintId,
      isDeleted: false,
      createdAt: now,
      updatedAt: now,
      deletedAt: null,
      sprintColor: null,
      creatorId: userId,
      workflowType: "SOIL_MOISTURE_TEST",
      requestedCount: 1,
      chainage: "Trial pit SP-02",
      truckDetails: "Truck allocation pending",
      sampleLabel: "SR-D1",
      initialWeight: null,
      finalWeight: null,
      moistureWeight: null,
      moisturePct: null,
      levelOneStatus: "PENDING",
      levelOneNote: null,
      levelTwoStatus: "PENDING",
      levelTwoNote: null,
      extraFields: Prisma.JsonNull,
    },
  ];

  return issues;
}
